export const data = [
  {
    id: "1",
    name: "Ava Patel",
    imageUrl:
      "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    company: "Nimbus Cloud",
    role: "VP Engineering",
    email: "ava@nimbuscloud.io",
    phone: "+1 (415) 555-0134",
    updatedAt: "2025-11-09T19:30:00Z",
    status: "Not signed",
    duration: "40 minutes ago",
    date: "N/A",
    summary:
      "Ava mentioned that they have no remaining budget for this quarter and therefore are not interested.",
    score: 0,
    tasks: [],
    timeline: [
      {
        id: 1,
        type: "email",
        content: "Sent pricing proposal to",
        target: "Ava Patel",
        date: "2h ago",
        datetime: "2025-11-08T10:00:00",
      },
      {
        id: 2,
        type: "call",
        content: "Security review call with",
        target: "Engineering team",
        date: "5h ago",
        datetime: "2025-11-08T07:00:00",
      },
      {
        id: 3,
        type: "meeting",
        content: "Scheduled deep-dive with",
        target: "Procurement",
        date: "1d ago",
        datetime: "2025-11-07T14:00:00",
      },
      {
        id: 4,
        type: "note",
        content: "Added internal note about",
        target: "EU cluster requirements",
        date: "2d ago",
        datetime: "2025-11-06T16:30:00",
      },
    ],
  },
  {
    id: "2",
    name: "Leo Zhang",
    imageUrl:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    company: "Marina Logistics",
    role: "Head of Ops",
    email: "leo@marinalogistics.com",
    phone: "+44 20 7946 0013",
    updatedAt: "2025-11-09T10:30:00Z",
    status: "Signed",
    duration: "3 hours ago",
    date: "Nov 4 2025 at 11:52 am",
    summary:
      "On-prem connector PoC requested. Legal redlines around indemnity cap. Waiting on COO sign-off.",
    score: 94,
    tasks: [
      {
        id: 1,
        title: "Propose compromise on indemnity cap",
        priority: "high",
        done: false,
      },
      {
        id: 2,
        title: "Send on-prem connector architecture diagram",
        priority: "med",
        done: false,
      },
    ],
    timeline: [
      {
        id: 1,
        type: "note",
        content: "Updated legal terms for",
        target: "indemnity cap",
        date: "3h ago",
        datetime: "2025-11-08T09:00:00",
      },
      {
        id: 2,
        type: "email",
        content: "Sent architecture diagram to",
        target: "Leo Zhang",
        date: "1d ago",
        datetime: "2025-11-07T11:00:00",
      },
      {
        id: 3,
        type: "meeting",
        content: "Discussed on-prem setup with",
        target: "Ops team",
        date: "3d ago",
        datetime: "2025-11-05T15:00:00",
      },
    ],
  },
  {
    id: "3",
    name: "Sofia Ramirez",
    imageUrl:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    company: "Aether Analytics",
    role: "Director of Data Strategy",
    email: "sofia@aetheranalytics.ai",
    phone: "+1 (646) 555-0197",
    updatedAt: "2025-11-08T21:15:00Z",
    status: "Signed",
    duration: "2 days ago",
    date: "Nov 2 2025 at 4:40 pm",
    summary:
      "Finalizing pilot results for predictive analytics module. Awaiting CISO approval for data-sharing agreement.",
    score: 86,
    tasks: [
      {
        id: 1,
        title: "Share pilot outcome deck",
        priority: "low",
        done: false,
      },
      {
        id: 2,
        title: "Confirm CISO review meeting time",
        priority: "med",
        done: false,
      },
    ],
    timeline: [
      {
        id: 1,
        type: "email",
        content: "Sent results summary to",
        target: "Sofia Ramirez",
        date: "6h ago",
        datetime: "2025-11-08T05:00:00",
      },
      {
        id: 2,
        type: "meeting",
        content: "Internal sync with",
        target: "Data science team",
        date: "1d ago",
        datetime: "2025-11-07T12:00:00",
      },
      {
        id: 3,
        type: "note",
        content: "Added observation about",
        target: "dataset quality variance",
        date: "2d ago",
        datetime: "2025-11-06T08:00:00",
      },
    ],
  },
  {
    id: "4",
    name: "Noah Williams",
    imageUrl:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    company: "Harbor Financial",
    role: "VP Risk & Compliance",
    email: "noah@harborfin.com",
    phone: "+1 (212) 555-0188",
    updatedAt: "2025-11-05T17:45:00Z",
    status: "Not signed",
    duration: "Oct 24 2025 at 2:12 pm",
    date: "N/A",
    summary:
      "Pending audit integration testing. Requires SOC2 and penetration test certificates for compliance documentation.",
    score: 0,
    tasks: [
      {
        id: 1,
        title: "Upload SOC2 report to portal",
        priority: "high",
        done: false,
      },
      {
        id: 2,
        title: "Schedule audit sync",
        priority: "low",
        done: false,
      },
    ],
    timeline: [
      {
        id: 1,
        type: "call",
        content: "Follow-up with",
        target: "Compliance team",
        date: "4h ago",
        datetime: "2025-11-08T08:30:00",
      },
      {
        id: 2,
        type: "note",
        content: "Added comment on",
        target: "SOC2 renewal timing",
        date: "1d ago",
        datetime: "2025-11-07T09:00:00",
      },
    ],
  },
  {
    id: "5",
    name: "Maya Chen",
    imageUrl:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    company: "Orbit Health Systems",
    role: "Chief Product Officer",
    email: "maya@orbithealth.io",
    phone: "+1 (310) 555-0172",
    updatedAt: "2025-11-09T03:15:00Z",
    status: "Signed",
    duration: "Oct 19 2025 at 10:32 am",
    date: "May 22 2025 at 6:30 pm",
    summary:
      "Product trial expanding to 10 new clinics. Legal reviewing HIPAA compliance. Marketing launch scheduled next week.",
    score: 51,
    tasks: [
      {
        id: 1,
        title: "Finalize HIPAA compliance checklist",
        priority: "high",
        done: false,
      },
      {
        id: 2,
        title: "Approve clinic rollout plan",
        priority: "med",
        done: false,
      },
      {
        id: 3,
        title: "Sign off on marketing assets",
        priority: "low",
        done: false,
      },
    ],
    timeline: [
      {
        id: 1,
        type: "email",
        content: "Received confirmation from",
        target: "Legal team",
        date: "1h ago",
        datetime: "2025-11-09T02:00:00",
      },
      {
        id: 2,
        type: "meeting",
        content: "Product expansion planning with",
        target: "Clinical partners",
        date: "1d ago",
        datetime: "2025-11-07T13:00:00",
      },
    ],
  },
];
